name: Semantic Versioning and Docker Build/Push

on:
  push:
    branches:
      - dev
      - stage
      - main
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  version_and_docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install semver
      run: |
        sudo npm install -g semver
      
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
      
    - name: Extract version from tag
      id: extract_version
      run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      
    - name: Determine version increment
      id: determine_version_increment
      run: |
        if [[ $GITHUB_REF =~ ^refs/heads/dev ]]; then
          echo "::set-output name=increment::patch"
        elif [[ $GITHUB_REF =~ ^refs/heads/stage ]]; then
          echo "::set-output name=increment::minor"
        elif [[ $GITHUB_REF =~ ^refs/heads/main ]]; then
          echo "::set-output name=increment::major"
        fi
    
    - name: Increment version
      id: increment_version
      run: |
        version=$(echo ${{ steps.extract_version.outputs.version }})
        increment=$(echo ${{ steps.determine_version_increment.outputs.increment }})
        new_version=$(semver bump $increment $version)
        echo "::set-output name=new_version::$new_version"
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build Docker image
      run: docker build -t prasad522/mavenwebapp:${{ steps.increment_version.outputs.new_version }} .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker image
      run: docker push prasad522/mavenwebapp:${{ steps.increment_version.outputs.new_version }}
